modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial-NoDerivs 3.0"

[[mods]]
modId="seasons_psyimagar"
version="1.0.0"
displayName="Seasons Psyimagar"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://gitee.com/abundant-season/abundant-season/raw/master/update.json"
logoFile="logo.png"
authors="default snowman"
description='''
Use the mana from seasons world!
'''

[[dependencies.seasons_psyimagar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




